// Browser check of the "Allow AI answers?" notice in the web assistant
// (rider dashboard; the rider iOS and Android apps show this page in a
// WebView). Desktop Chromium at phone size: NOT a device test. The
// assistant and consent routes are stubbed in the browser, so no model is
// called; the notice text is the server's own (lib/agent/aiConsent.js).
// Writes screenshots to docs/screenshots/ai-consent/ when
// CONSENT_SCREENSHOTS=1.
//
// Needs Playwright and Chromium; skips without them. Run with:
//   NODE_PATH="$(npm root -g)" npx jest test/rider-assistant-consent.browser
process.env.NODE_ENV = "test";
process.env.SUPABASE_URL = "http://localhost:54321";
process.env.SUPABASE_SERVICE_ROLE_KEY = "test-service-role-key";
process.env.RIDER_SESSION_SECRET = "test-rider-session-secret";
process.env.DRIVER_SESSION_SECRET = "test-driver-session-secret";
process.env.RIDE_QUOTE_SECRET = "test-ride-quote-secret";
process.env.ADMIN_API_TOKEN = "test-admin-token";
delete process.env.CANONICAL_HOST;
delete process.env.FOUNDATION_HOST;
delete process.env.AGENT_LLM_BASE_URL;
delete process.env.ANTHROPIC_API_KEY;

const { createFakeSupabase } = require("./fakeSupabase");
const { makeRider, makeDriver } = require("./rideTestHelpers");

let mockSupabaseClient;
jest.mock("@supabase/supabase-js", () => ({ createClient: () => mockSupabaseClient }));

let chromium = null;
try {
  // eslint-disable-next-line global-require, import/no-unresolved
  ({ chromium } = require("playwright"));
} catch (error) {
  chromium = null;
}
const describeWithBrowser = chromium ? describe : describe.skip;
jest.setTimeout(90000);

const HOST = "harveytaxiservice.test";

const fs = require("fs");
const path = require("path");
const { consentText } = require("../lib/agent/aiConsent");

const NOTICE = { required: true, ...consentText("rider") };
const SHOTS = process.env.CONSENT_SCREENSHOTS === "1" ? path.join(__dirname, "..", "docs", "screenshots", "ai-consent") : null;

describeWithBrowser("Allow AI answers? (rider web assistant, also inside the rider apps)", () => {
  let server;
  let browser;
  let base;
  beforeAll(async () => {
    mockSupabaseClient = createFakeSupabase({
      riders: [makeRider()],
      drivers: [makeDriver()],
      rides: [],
      audit_logs: [],
      system_flags: [{ key: "agent_assist_enabled", value: "true" }, { key: "agent_kill_switch", value: "false" }]
    });
    // eslint-disable-next-line global-require
    const { app } = require("../server");
    server = await new Promise((resolve) => {
      const s = app.listen(0, "127.0.0.1", () => resolve(s));
    });
    base = `http://${HOST}:${server.address().port}`;
    browser = await chromium.launch({ args: [`--host-resolver-rules=MAP ${HOST} 127.0.0.1`] });
    if (SHOTS) fs.mkdirSync(SHOTS, { recursive: true });
  });
  afterAll(async () => {
    if (browser) await browser.close();
    if (server) {
      if (server.closeAllConnections) server.closeAllConnections();
      await new Promise((r) => server.close(r));
    }
  });

  // Stubs the assistant routes in the browser: no model is called.
  async function open({ granted = false } = {}) {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
    await context.route(/^https?:\/\/(?!harveytaxiservice\.test)/, (route) => route.abort());
    const calls = { assist: [], consent: [] };
    let allowed = granted;
    await context.route("**/api/agent/rider/ai-consent", (route) => {
      const req = route.request();
      if (req.method() === "POST") {
        const b = JSON.parse(req.postData() || "{}");
        calls.consent.push(b);
        allowed = b.granted === true;
      }
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ ok: true, ai_available: true, consent: { granted: allowed, version: NOTICE.version }, notice: NOTICE }) });
    });
    await context.route("**/api/agent/rider/assist", (route) => {
      const b = JSON.parse(route.request().postData() || "{}");
      calls.assist.push(b);
      const answer = allowed
        ? { ok: true, agent_available: true, reply: "Your driver is about 6 minutes away.", source: "model", actions: [], sources: [], answered_by: { engine: "model", label: "AI-generated by Harvey Assistant" } }
        : { ok: true, agent_available: true, reply: "Your ride is on the way. Open Track ride to see your driver.", source: "rules", actions: [], sources: [], ai_consent: NOTICE };
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(answer) });
    });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(`${base}/rider-dashboard.html`);
    await page.waitForSelector("[data-testid=hta-launcher]", { timeout: 20000 });
    await page.click("[data-testid=hta-launcher]");
    const ask = async (q) => {
      await page.fill("#htaPanel input[type=text]", q);
      await page.press("#htaPanel input[type=text]", "Enter");
    };
    return { context, page, errors, calls, ask };
  }

  test("the notice appears with the server's text; Allow records it, repeats the question once, and labels the AI answer; Turn off stops it", async () => {
    const { context, page, errors, calls, ask } = await open();
    await ask("where is my driver?");
    await page.waitForSelector("[data-testid=hta-consent]", { timeout: 15000 });
    const card = await page.textContent("[data-testid=hta-consent]");
    expect(card).toContain("Allow AI answers?");
    expect(card).toContain("Claude, an AI model made by Anthropic");
    expect(card).toContain("never sent to the AI");
    expect(card).toContain("You can turn AI answers off at any time");
    expect(await page.getAttribute("[data-testid=hta-consent] a", "href")).toBe("/privacy-policy.html");
    expect(await page.isVisible("[data-testid=hta-ai-bar]")).toBe(false);
    if (SHOTS) await page.locator("#htaPanel").screenshot({ path: path.join(SHOTS, "rider-1-notice.png") });

    await page.click("[data-testid=hta-consent-allow]");
    await page.waitForSelector(".hta-ai", { timeout: 15000 });
    expect(calls.consent).toEqual([{ granted: true, version: NOTICE.version }]);
    expect(calls.assist).toHaveLength(2);
    expect(calls.assist[1].message).toBe("where is my driver?");
    // The repeated question isn't also in its own context.
    expect(calls.assist[1].context.some((t) => t.text === "where is my driver?")).toBe(false);
    expect(await page.$$eval("#htaPanel .hta-me", (els) => els.length)).toBe(1);
    expect(await page.isVisible("[data-testid=hta-ai-bar]")).toBe(true);
    expect(await page.$("[data-testid=hta-consent]")).toBeNull();
    if (SHOTS) await page.locator("#htaPanel").screenshot({ path: path.join(SHOTS, "rider-2-ai-answer.png") });

    await page.click("[data-testid=hta-ai-off]");
    await page.waitForFunction(() => document.querySelector("[data-testid=hta-ai-bar]").hidden === true);
    expect(calls.consent[1]).toEqual({ granted: false });
    expect(errors).toEqual([]);
    await context.close();
  });

  test("Not now: nothing allowed, the standard assistant keeps answering, and the notice isn't repeated this visit", async () => {
    const { context, page, errors, calls, ask } = await open();
    await ask("where is my driver?");
    await page.waitForSelector("[data-testid=hta-consent]", { timeout: 15000 });
    await page.click("[data-testid=hta-consent-decline]");
    await page.waitForFunction(() => /Nothing was sent to the AI/.test(document.querySelector("#htaPanel .hta-log").textContent));
    expect(calls.consent).toEqual([{ granted: false }]);
    await ask("what's my fare?");
    await page.waitForFunction(() => document.querySelectorAll("#htaPanel .hta-bot").length >= 4);
    expect(await page.$("[data-testid=hta-consent]")).toBeNull();
    expect(await page.$(".hta-ai")).toBeNull();
    expect(errors).toEqual([]);
    await context.close();
  });

  test("already allowed: the bar shows on open and no notice is shown", async () => {
    const { context, page, errors, ask } = await open({ granted: true });
    await page.waitForSelector("[data-testid=hta-ai-bar]:not([hidden])", { timeout: 15000 });
    await ask("where is my driver?");
    await page.waitForSelector(".hta-ai", { timeout: 15000 });
    expect(await page.$("[data-testid=hta-consent]")).toBeNull();
    expect(errors).toEqual([]);
    await context.close();
  });
});
