// Browser check of the answer labels in the web assistant (rider
// dashboard; the rider iOS and Android apps show this page in a WebView).
// Desktop Chromium at phone size: NOT a device test.
// - A model-written answer shows "AI-generated by Harvey Assistant".
// - A specialist answer shows "Answered by … for … · Rules-based (no AI
//   model)" and no AI label.
// - A rules answer shows neither.
// The assist responses are stubbed in the browser, so no model is called.
//
// Needs Playwright and Chromium; skips without them. Run with:
//   NODE_PATH="$(npm root -g)" npx jest test/rider-assistant-labels.browser
process.env.NODE_ENV = "test";
process.env.SUPABASE_URL = "http://localhost:54321";
process.env.SUPABASE_SERVICE_ROLE_KEY = "test-service-role-key";
process.env.RIDER_SESSION_SECRET = "test-rider-session-secret";
process.env.DRIVER_SESSION_SECRET = "test-driver-session-secret";
process.env.RIDE_QUOTE_SECRET = "test-ride-quote-secret";
process.env.ADMIN_API_TOKEN = "test-admin-token";
delete process.env.CANONICAL_HOST;
delete process.env.FOUNDATION_HOST;
delete process.env.AGENT_LLM_BASE_URL;
delete process.env.ANTHROPIC_API_KEY;

const { createFakeSupabase } = require("./fakeSupabase");
const { makeRider, makeDriver } = require("./rideTestHelpers");

let mockSupabaseClient;
jest.mock("@supabase/supabase-js", () => ({ createClient: () => mockSupabaseClient }));

let chromium = null;
try {
  // eslint-disable-next-line global-require, import/no-unresolved
  ({ chromium } = require("playwright"));
} catch (error) {
  chromium = null;
}
const describeWithBrowser = chromium ? describe : describe.skip;
jest.setTimeout(90000);

const HOST = "harveytaxiservice.test";

const ANSWERS = [
  { ok: true, agent_available: true, reply: "Hi there! Ask me about your ride.", source: "model", actions: [], sources: [], answered_by: { engine: "model", label: "AI-generated by Harvey Assistant" } },
  {
    ok: true,
    agent_available: true,
    reply: "I can prepare a request to Harvey Taxi support from this conversation.",
    source: "rules",
    actions: [],
    sources: [],
    specialist: { id: "customer_support", name: "Customer Support", chief: "Support Handoff", engine: "rules", engine_label: "Rules-based (no AI model)" }
  },
  { ok: true, agent_available: true, reply: "I can help you book a ride.", source: "rules", actions: [], sources: [] }
];

describeWithBrowser("web assistant answer labels (rider apps' WebView)", () => {
  let server;
  let browser;
  let base;
  beforeAll(async () => {
    mockSupabaseClient = createFakeSupabase({
      riders: [makeRider()],
      drivers: [makeDriver()],
      rides: [],
      audit_logs: [],
      system_flags: [{ key: "agent_assist_enabled", value: "true" }, { key: "agent_kill_switch", value: "false" }]
    });
    // eslint-disable-next-line global-require
    const { app } = require("../server");
    server = await new Promise((resolve) => {
      const s = app.listen(0, "127.0.0.1", () => resolve(s));
    });
    base = `http://${HOST}:${server.address().port}`;
    browser = await chromium.launch({ args: [`--host-resolver-rules=MAP ${HOST} 127.0.0.1`] });
  });
  afterAll(async () => {
    if (browser) await browser.close();
    if (server) {
      if (server.closeAllConnections) server.closeAllConnections();
      await new Promise((r) => server.close(r));
    }
  });

  test("AI-generated, specialist and rules answers are each labelled correctly", async () => {
    const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await context.route(/^https?:\/\/(?!harveytaxiservice\.test)/, (route) => route.abort());
    let n = 0;
    await context.route("**/api/agent/rider/assist", (route) => {
      const body = ANSWERS[n] || ANSWERS[ANSWERS.length - 1];
      n += 1;
      route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(body) });
    });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await page.goto(`${base}/rider-dashboard.html`);
    await page.waitForSelector("[data-testid=hta-launcher]", { timeout: 20000 });
    await page.click("[data-testid=hta-launcher]");
    const ask = async (q, count) => {
      await page.fill("#htaPanel input[type=text]", q);
      await page.press("#htaPanel input[type=text]", "Enter");
      await page.waitForFunction((c) => document.querySelectorAll("#htaPanel .hta-bot").length >= c, count, { timeout: 15000 });
    };
    await ask("hello", 2);
    await ask("I want to contact support", 3);
    await ask("book a ride", 4);
    const bots = await page.$$eval("#htaPanel .hta-bot", (els) =>
      els.map((e) => Array.from(e.querySelectorAll(".hta-src")).map((s) => s.textContent.trim()))
    );
    // bots[0] is the greeting.
    expect(bots[1]).toEqual(["AI-generated by Harvey Assistant"]);
    expect(bots[2]).toEqual(["Answered by Customer Support for Support Handoff · Rules-based (no AI model)"]);
    expect(bots[3]).toEqual([]);
    expect(errors).toEqual([]);
    await context.close();
  });
});
