#!/usr/bin/env node
// End-to-end demonstration of the operations assistant using the LABELLED
// TEST CASES in test/fixtures/opsScenarios.js. Runs the real server in
// this process with an in-memory database (never Supabase, never Stripe)
// and writes what the API actually returned to
// docs/agent-operations/demo-transcript.md.
//   node scripts/ops-demo.js

const fs = require("fs");
const path = require("path");
const Module = require("module");

Object.assign(process.env, {
  NODE_ENV: "test",
  SUPABASE_URL: "http://localhost:54321",
  SUPABASE_SERVICE_ROLE_KEY: "demo-not-a-real-key",
  RIDER_SESSION_SECRET: "demo-rider-secret",
  DRIVER_SESSION_SECRET: "demo-driver-secret",
  RIDE_QUOTE_SECRET: "demo-quote-secret",
  ADMIN_API_TOKEN: "demo-admin-token",
  ADMIN_EMAIL: "demo-admin@example.test",
  API_RATE_LIMIT_PER_MINUTE: "100000",
  HARVEY_ISOLATED_TEST: "1",
  OPS_CASES_PER_MINUTE: "100000"
});
delete process.env.OPENAI_API_KEY;
delete process.env.STRIPE_SECRET_KEY;
delete process.env.AGENT_LLM_BASE_URL;

const { createFakeSupabase } = require("../test/fakeSupabase");
const { buildSeed, DEMO } = require("../test/fixtures/opsScenarios");
const { signTestRiderToken, riderAuthHeaders } = require("../test/rideTestHelpers");

const seed = buildSeed(Date.now());
seed.system_flags = [
  { key: "ops_assistant_enabled", value: "true" },
  // Demo environment only: lets staff approval actually run an action.
  { key: "ops_actions_enabled", value: "true" }
];
const db = createFakeSupabase(seed);
db.rpc = async (fn) => (fn === "dispatch_ride_atomic" ? { data: null, error: { message: "not available in demo database" } } : { data: null, error: null });

const realLoad = Module._load;
Module._load = function load(request, parent, isMain) {
  if (request === "@supabase/supabase-js") return { createClient: () => db };
  return realLoad.call(this, request, parent, isMain);
};
const silence = ["log", "warn", "info"].map((k) => [k, console[k]]);
console.log = console.warn = console.info = () => {};
const { app } = require("../server");
for (const [k, fn] of silence) console[k] = fn;

const request = require("supertest");
const ADMIN = { "x-admin-token": process.env.ADMIN_API_TOKEN };
const RIDER = riderAuthHeaders(signTestRiderToken("TEST-RIDER-A"));

const out = [];
const md = (s = "") => out.push(s);
const list = (items, fmt) => (items.length ? items.forEach((i) => md(`- ${fmt(i)}`)) : md("- (none)"));

function caseSection(c) {
  const s = c.summary;
  md(`**State:** ${c.state} | **Case:** ${c.id} | **Ride:** ${c.ride_id}`);
  md();
  md(`**Decision summary:** ${s.decision_summary}`);
  md();
  for (const f of s.findings) {
    md(`#### ${f.title}`);
    md("Verified facts:");
    list(f.facts, (x) => `${x.text} _(${x.source})_`);
    md("Conflicts:");
    list(f.conflicts, (x) => `Report: ${x.claim} / Records: ${x.evidence} → ${x.reading} _(${x.source})_`);
    md("Missing information:");
    list(f.missing, (x) => `${x.text} (${x.why})`);
    md("Hypotheses (unverified):");
    list(f.hypotheses, (x) => `${x.text} (basis: ${x.basis})`);
    md();
  }
  md("Timeline:");
  list(s.timeline, (e) => `${e.at} ${e.label} _(${e.source})_`);
  md();
  md("Policy checks:");
  list(s.checks, (k) => `${k.action}: ${k.allowed ? "allowed" : "blocked"} (${k.reason})`);
  md("Action queue:");
  list(c.queue, (q) => `${q.id} ${q.label}: ${q.status}, confirmed by ${q.confirm_by}${q.result ? `, result ${JSON.stringify(q.result)}` : ""}`);
  md("Workflow steps:");
  list(c.steps, (st) => `${st.step}: ${st.status}${st.detail ? ` (${st.detail})` : ""}`);
  md("Policy references:");
  list(s.policy_refs, (p) => `${p.id} ${p.title} (${p.source})`);
  md();
}

(async () => {
  const started = new Date().toISOString();
  md("# Operations assistant: end-to-end demonstration");
  md();
  md("> **TEST DATA ONLY.** Every ride, rider and driver below is a labelled fixture from `test/fixtures/opsScenarios.js`. The run used an in-memory database; nothing touched Supabase, Stripe or production.");
  md(`> Generated by \`node scripts/ops-demo.js\` at ${started}. All output below is what the API returned.`);
  md();

  // 1. Complicated issue, investigated.
  md(`## ${DEMO.complicated.label}`);
  md(`Rider message: "${DEMO.complicated.message}"`);
  md();
  let r = await request(app).post("/api/ops/rider/cases").set(RIDER).send({ message: DEMO.complicated.message, ride_id: DEMO.complicated.rideId });
  md("What the rider sees (`POST /api/ops/rider/cases`):");
  md("```json");
  md(JSON.stringify(r.body.case, null, 2));
  md("```");
  const c1 = (await request(app).get(`/api/admin/ops/cases/${r.body.case.case_id}`).set(ADMIN)).body.case;
  md("What staff see:");
  md();
  caseSection(c1);
  md("The rider then confirms the no-fee cancellation in the app (existing `POST /api/rides/:id/cancel`):");
  const cancel = await request(app).post(`/api/rides/${DEMO.complicated.rideId}/cancel`).set(RIDER).send({ reason: "driver did not arrive" });
  md(`- cancel route returned HTTP ${cancel.status}`);
  const c1b = (await request(app).get(`/api/admin/ops/cases/${c1.id}`).set(ADMIN)).body.case;
  md(`- case re-checked the ride record: action ${c1b.queue[0].id} is now **${c1b.queue[0].status}**, observed ${JSON.stringify(c1b.queue[0].result && c1b.queue[0].result.observed)}; the case stays **${c1b.state}** for the driver-conduct review.`);
  md();

  // 2. Authorized action, executed and verified.
  md(`## ${DEMO.action.label}`);
  md(`Staff note: "${DEMO.action.message}"`);
  md();
  r = await request(app).post("/api/admin/ops/cases").set(ADMIN).send({ ride_id: DEMO.action.rideId, message: DEMO.action.message });
  const c2 = r.body.case;
  md("Investigation and plan:");
  md();
  caseSection(c2);
  const approve = await request(app).post(`/api/admin/ops/cases/${c2.id}/actions/A1/approve`).set(ADMIN).send({});
  md(`Staff approved action A1 (HTTP ${approve.status}). Outcome as returned and verified from the database:`);
  md("```json");
  md(JSON.stringify(approve.body.outcome, null, 2));
  md("```");
  md();
  caseSection(approve.body.case);
  const again = await request(app).post(`/api/admin/ops/cases/${c2.id}/actions/A1/approve`).set(ADMIN).send({});
  md(`A second approval of the same action returned HTTP ${again.status}: "${again.body.error}". Pending offers for the ride: ${db._state.driver_offers.filter((o) => o.ride_id === DEMO.action.rideId && o.status === "pending").length}.`);
  md();

  // 3. Escalation.
  md(`## ${DEMO.escalation.label}`);
  md(`Rider message: "${DEMO.escalation.message}"`);
  md();
  r = await request(app).post("/api/ops/rider/cases").set(RIDER).send({ message: DEMO.escalation.message, ride_id: DEMO.escalation.rideId });
  md("What the rider sees:");
  md("```json");
  md(JSON.stringify(r.body.case, null, 2));
  md("```");
  const c3 = (await request(app).get(`/api/admin/ops/cases/${r.body.case.case_id}`).set(ADMIN)).body.case;
  caseSection(c3);

  // Activity log.
  md("## Agent activity recorded (audit_logs)");
  const activity = db._state.audit_logs.filter((a) => /^ops\./.test(a.action));
  list(activity, (a) => `${a.created_at || ""} ${a.action} ${a.entity_id || ""} ${JSON.stringify(a.metadata || {})}`);

  const file = path.join(__dirname, "..", "docs", "agent-operations", "demo-transcript.md");
  fs.writeFileSync(file, out.join("\n") + "\n");
  console.log(`Wrote ${path.relative(process.cwd(), file)}: case 1 ${c1b.state}, case 2 ${approve.body.case.state} (verified ${approve.body.outcome.verified}), case 3 ${c3.state}`);
  process.exit(0);
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
