// Explicit permission before a question goes to the AI provider
// (docs/ai-model.md, "Consent"). App Store Review Guideline 5.1.2(i):
// "You must clearly disclose where personal data will be shared with third
// parties, including with third-party AI, and obtain explicit permission
// before doing so."
//
// - The server keeps one row per decision in agent_ai_consents (append-only;
//   the latest row for an account decides). No row means no permission.
// - Permission is tied to AI_CONSENT_VERSION. Changing what is sent or who
//   receives it means a new version, and everyone is asked again.
// - Every client shows the text below exactly as the server sends it, so
//   the rider web assistant (also inside the rider apps) and the driver app
//   can't drift apart.
// - Without permission the assistant still answers, from rules and approved
//   pages, exactly as it does for accounts the model isn't enabled for.

const AI_CONSENT_VERSION = "2026-10-10";
const AI_CONSENT_TABLE = "agent_ai_consents";

const DETAILS = Object.freeze({
  rider: "your ride status, your driver's first name and vehicle, the pickup estimate and the fare",
  driver: "your ride offers, trip steps and addresses, earnings and hours online"
});

function consentText(role) {
  const r = role === "driver" ? "driver" : "rider";
  return {
    version: AI_CONSENT_VERSION,
    title: "Allow AI answers?",
    body:
      "Harvey Assistant can write answers with Claude, an AI model made by Anthropic. " +
      "If you allow this, what you type, your recent messages in this chat, and the details needed to answer " +
      `(${DETAILS[r]}) are sent to Anthropic, which writes the answer for Harvey Taxi as our service provider.`,
    points: [
      'AI-written answers are marked "AI-generated by Harvey Assistant".',
      "Messages the assistant recognises as an emergency, fraud, a disputed charge, a refund or an account suspension are never sent to the AI. They get Harvey Taxi's standard guidance and are passed to our staff.",
      "Don't type card numbers, passwords or other private details in the chat.",
      "You can turn AI answers off at any time in Harvey Assistant. You'll still get answers from Harvey Taxi's standard assistant."
    ],
    allow: "Allow AI answers",
    decline: "Not now",
    turn_off: "Turn off AI answers",
    privacy_url: "https://harveytaxiservice.com/privacy-policy.html#harvey-assistant",
    // Same page as a site path, for the web assistant (same-origin links only).
    privacy_path: "/privacy-policy.html"
  };
}

// Latest decision from agent_ai_consents rows (newest first or any order).
function currentConsent(rows) {
  const list = Array.isArray(rows) ? rows.filter(Boolean) : [];
  if (!list.length) return { granted: false, version: null, decided_at: null };
  const latest = list.reduce((a, b) => (String(b.created_at || "") > String(a.created_at || "") ? b : a));
  const granted = latest.granted === true && latest.consent_version === AI_CONSENT_VERSION;
  return { granted, version: latest.consent_version || null, decided_at: latest.created_at || null, stale: latest.granted === true && !granted };
}

// Validates a POST body: { granted: true|false, version }.
function validateConsentChange(body) {
  if (!body || typeof body.granted !== "boolean") return { ok: false, error: "granted must be true or false." };
  if (body.granted && body.version !== AI_CONSENT_VERSION) {
    return { ok: false, stale: true, error: "The AI notice has changed. Please read the current notice before allowing AI answers." };
  }
  return { ok: true, granted: body.granted };
}

module.exports = { AI_CONSENT_VERSION, AI_CONSENT_TABLE, consentText, currentConsent, validateConsentChange };
