// Who may get model-powered answers (docs/ai-model.md).
//
// system_flags.agent_model_mode:
//   "off"           - everyone gets the rules-based assistant (default).
//   "test_accounts" - only accounts listed in agent_model_test_accounts
//                     (synthetic test riders/drivers) get the model.
//   "all"           - every signed-in rider and driver. Refused unless the
//                     owner has approved the privacy disclosure and set
//                     AGENT_MODEL_PUBLIC_APPROVED=true on the server; until
//                     then it acts as "test_accounts".
// Signed-out visitors never get the model.
//
// system_flags.agent_model_driver_scope ("test_accounts" by default, or
// "all"): drivers follow "all" only when this is also "all", so the rider
// rollout never reaches drivers by itself. A driver using the native
// driver app additionally needs an app that shows the "AI-generated by
// Harvey Assistant" label (it sends capabilities: ["ai_label"]); older
// builds keep rules-based answers. Listed test accounts are exempt from
// the driver scope, but not from the label: every driver app build must
// show it before it gets a model answer.
//
// Being eligible is not enough on its own: the account must also have
// given explicit permission to send its questions to the AI provider
// (lib/agent/aiConsent.js). That check is in server.js.
//
// system_flags.agent_specialist_scope (who the switched-on specialists
// answer): "off", "test_accounts" (default) or "all" (every rider and
// driver; signed-out visitors get general guidance only). "test_accounts"
// uses its own list, system_flags.agent_specialist_test_accounts, so
// taking an account off the model list doesn't take away its rules-based
// specialists. Until that list is set, the model list is used (the
// behaviour before the lists were separated). A specialist still needs its
// own agent_specialist_*_enabled switch.

const MODEL_MODES = Object.freeze(["off", "test_accounts", "all"]);
const SCOPES = Object.freeze(["off", "test_accounts", "all"]);
const DRIVER_SCOPES = Object.freeze(["test_accounts", "all"]);
const MODEL_FLAG_KEYS = Object.freeze({
  MODE: "agent_model_mode",
  TEST_ACCOUNTS: "agent_model_test_accounts",
  DRIVER_SCOPE: "agent_model_driver_scope",
  SPECIALIST_SCOPE: "agent_specialist_scope",
  SPECIALIST_TEST_ACCOUNTS: "agent_specialist_test_accounts"
});
// What a client must declare before a non-test account gets model answers
// in it. Only the native driver app is checked; the web assistant (used by
// the rider apps and the web driver dashboard) always shows the label.
const AI_LABEL_CAPABILITY = "ai_label";
const MAX_TEST_ACCOUNTS = 25;
const ACCOUNT_KEY = /^(rider|driver):[A-Za-z0-9_.:-]{1,80}$/;

function publicApproved(env = process.env) {
  return String(env.AGENT_MODEL_PUBLIC_APPROVED || "").trim().toLowerCase() === "true";
}

function parseTestAccounts(value) {
  let list = [];
  try {
    list = Array.isArray(value) ? value : JSON.parse(String(value || "[]"));
  } catch {
    list = [];
  }
  if (!Array.isArray(list)) return [];
  return [...new Set(list.map((x) => String(x).trim()).filter((x) => ACCOUNT_KEY.test(x)))].slice(0, MAX_TEST_ACCOUNTS);
}

function resolveModelPolicy(rows, { env = process.env } = {}) {
  const get = (key) => {
    const row = (rows || []).find((r) => r.key === key);
    return row ? row.value : null;
  };
  const stored = MODEL_MODES.includes(get(MODEL_FLAG_KEYS.MODE)) ? get(MODEL_FLAG_KEYS.MODE) : "off";
  const approved = publicApproved(env);
  const effective = stored === "all" && !approved ? "test_accounts" : stored;
  const driverScope = DRIVER_SCOPES.includes(get(MODEL_FLAG_KEYS.DRIVER_SCOPE)) ? get(MODEL_FLAG_KEYS.DRIVER_SCOPE) : "test_accounts";
  const specialistScope = SCOPES.includes(get(MODEL_FLAG_KEYS.SPECIALIST_SCOPE)) ? get(MODEL_FLAG_KEYS.SPECIALIST_SCOPE) : "test_accounts";
  const testAccounts = parseTestAccounts(get(MODEL_FLAG_KEYS.TEST_ACCOUNTS));
  const specialistList = get(MODEL_FLAG_KEYS.SPECIALIST_TEST_ACCOUNTS);
  return {
    stored_mode: stored,
    mode: effective,
    public_approved: approved,
    test_accounts: testAccounts,
    driver_scope: driverScope,
    specialist_scope: specialistScope,
    specialist_test_accounts: specialistList === null ? testAccounts : parseTestAccounts(specialistList),
    // "own" once agent_specialist_test_accounts is set; "model_list" before.
    specialist_accounts_source: specialistList === null ? "model_list" : "own"
  };
}

function accountKey(role, actor) {
  return `${role === "driver" ? "driver" : "rider"}:${actor.id}`;
}

function isTestAccount(policy, { role, actor }) {
  if (!policy || !actor || !actor.id) return false;
  return (policy.test_accounts || []).includes(accountKey(role, actor));
}

function isSpecialistTestAccount(policy, { role, actor }) {
  if (!policy || !actor || !actor.id) return false;
  const list = Array.isArray(policy.specialist_test_accounts) ? policy.specialist_test_accounts : policy.test_accounts || [];
  return list.includes(accountKey(role, actor));
}

function hasAiLabel(capabilities) {
  return Array.isArray(capabilities) && capabilities.includes(AI_LABEL_CAPABILITY);
}

// `client` is "driver_app" for the native driver app, anything else for the
// web assistant; `capabilities` is what that client declared.
function modelEligibility(policy, { role, actor, client = "web", capabilities = [] }) {
  if (!policy || policy.mode === "off") return { eligible: false, reason: "model_off" };
  if (!actor || !actor.id) return { eligible: false, reason: "signed_out" };
  // The driver app must show "AI-generated by Harvey Assistant" before any
  // model answer reaches it, test accounts included.
  if (role === "driver" && client === "driver_app" && !hasAiLabel(capabilities)) return { eligible: false, reason: "app_lacks_ai_label" };
  if (isTestAccount(policy, { role, actor })) return { eligible: true, reason: null };
  if (policy.mode !== "all") return { eligible: false, reason: "not_a_test_account" };
  if (role === "driver") {
    if (policy.driver_scope !== "all") return { eligible: false, reason: "drivers_not_enabled" };
    if (client === "driver_app" && !hasAiLabel(capabilities)) return { eligible: false, reason: "app_lacks_ai_label" };
  }
  return { eligible: true, reason: null };
}

// Whether switched-on specialists answer this account.
function specialistEligibility(policy, { role, actor }) {
  const scope = policy ? policy.specialist_scope : "test_accounts";
  if (scope === "off") return false;
  // "all" includes signed-out visitors, who get general guidance only
  // (specialists read nothing without a session).
  if (scope === "all") return true;
  return isSpecialistTestAccount(policy, { role, actor });
}

// Validates an admin change. Returns { ok, error, value }.
function validateAccountList(list, field) {
  if (!Array.isArray(list)) return { ok: false, error: `${field} must be a list like ["rider:ID", "driver:ID"].` };
  const parsed = parseTestAccounts(list);
  if (parsed.length !== list.length) return { ok: false, error: `Each entry in ${field} must look like rider:ID or driver:ID (at most ${MAX_TEST_ACCOUNTS}).` };
  return { ok: true, value: parsed };
}

function validateModelSettings({ mode, testAccounts, driverScope, specialistScope, specialistTestAccounts }, { env = process.env } = {}) {
  const out = {};
  if (mode !== undefined) {
    if (!MODEL_MODES.includes(mode)) return { ok: false, error: "mode must be off, test_accounts or all." };
    if (mode === "all" && !publicApproved(env)) {
      return { ok: false, error: "The model can't be enabled for all users until the owner approves the privacy disclosure and sets AGENT_MODEL_PUBLIC_APPROVED=true." };
    }
    out.mode = mode;
  }
  if (testAccounts !== undefined) {
    const list = validateAccountList(testAccounts, "test_accounts");
    if (!list.ok) return { ok: false, error: list.error };
    out.testAccounts = list.value;
  }
  if (specialistTestAccounts !== undefined) {
    const list = validateAccountList(specialistTestAccounts, "specialist_test_accounts");
    if (!list.ok) return { ok: false, error: list.error };
    out.specialistTestAccounts = list.value;
  }
  if (driverScope !== undefined) {
    if (!DRIVER_SCOPES.includes(driverScope)) return { ok: false, error: "driver_scope must be test_accounts or all." };
    out.driverScope = driverScope;
  }
  if (specialistScope !== undefined) {
    if (!SCOPES.includes(specialistScope)) return { ok: false, error: "specialist_scope must be off, test_accounts or all." };
    out.specialistScope = specialistScope;
  }
  return { ok: true, error: null, value: out };
}

module.exports = {
  MODEL_MODES,
  MODEL_FLAG_KEYS,
  AI_LABEL_CAPABILITY,
  publicApproved,
  parseTestAccounts,
  resolveModelPolicy,
  modelEligibility,
  specialistEligibility,
  validateModelSettings
};
